### ISSUE TITLE
AttributeError: 'MyApi' object has no attribute '_environment'

### ISSUE THREAD

**Issue by estahn** [fern-api/fern-python#289]
Config:
```yaml
default-group: local
groups:
  local:
    generators:
      - name: fernapi/fern-python-sdk
        version: 0.3.8-rc6
```

Generated Client:
```python
class MyApi:
    def __init__(
        self,
        *,
        environment:MyApiEnvironment = MyApiEnvironment.DEFAULT,
        timeout: typing.Optional[float] = 60,
    ):
        self._client_wrapper = SyncClientWrapper(httpx_client=httpx.Client(timeout=timeout))

    def login(
        self, *, user_account: str, user_password: str, appkey: str, lang: typing.Optional[str] = OMIT, sys_code: int
    ) -> LoginResponse:
```

Error:
```shell
Traceback (most recent call last):
  File ".../generated/test.py", line 6, in <module>
    response = client.login(
  File ".../generated/sungrow_sdk/client.py", line 48, in login
    urllib.parse.urljoin(f"{self._environment.value}/", "login"),
AttributeError: 'MyApi' object has no attribute '_environment'
```

**Comment by dsinghvi** [comment]
This is fixed in https://github.com/fern-api/fern-python/releases/tag/0.3.8-rc7
